TARGET := iphone:clang:9.3:5.0
ARCHS := armv7

THEOS_PACKAGE_FORMAT = ipa

include $(THEOS)/makefiles/common.mk

APPLICATION_NAME := RetroChat
RetroChat_FILES := main.m AppDelegate.m AuthViewController.m ChatsListViewController.m ChatViewController.m
RetroChat_FRAMEWORKS := UIKit CoreGraphics Foundation

include $(THEOS)/makefiles/application.mk





