name: Build RetroChat IPA

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Theos and Download Legacy SDK
      run: |
        git clone --recursive https://github.com/theos/theos.git $HOME/theos
        rm -rf $HOME/theos/sdks/*
        
        # Скачиваем официальный iOS 9.3 SDK, который умеет собирать под iOS 5.0 armv7
        curl -ksL https://github.com/theos/sdks/raw/master/iPhoneOS9.3.sdk.tar.xz -o sdk.tar.xz
        tar -xf sdk.tar.xz -C $HOME/theos/sdks/
        rm sdk.tar.xz
        
        echo "THEOS=$HOME/theos" >> $GITHUB_ENV

    - name: Compile iOS Application to IPA
      run: |
        export THEOS=$HOME/theos
        cd Applications
        make package FINALPACKAGE=1 THEOS_SCHEMA=iOS ARCHS=armv7

    - name: Upload Finished IPA
      uses: actions/upload-artifact@v4
      with:
        name: RetroChat-iOS5-6-IPA
        path: Applications/packages/*.ipa
























